#!/bin/bash

# acrordrdc env
progHome="$WINEPREFIX/drive_c/Program Files/Adobe/Acrobat Reader 2017/Reader"
progBin="AcroRd32.exe"
progSetup="$WINEPREFIX/drive_c/Program Files/Adobe/Acrobat Reader 2017/Setup Files/{AC76BA86-7AD7-FFFF-7B44-AE1108756300}/"

$WINETRICKS --unattended mspatcha riched20 win7

INSTALL_URL_US="https://ardownload2.adobe.com/pub/adobe/reader/win/Acrobat2017/1700830051/AcroRdr20171700830051_MUI.exe"
INSTALL_URL_UPD="https://ardownload2.adobe.com/pub/adobe/reader/win/Acrobat2017/YYY/AcroRdr2017UpdYYY_MUI.msp"

# If we've been given and installer URL derive the filename
if [ -n "${INSTALL_URL_UPD}" ]; then
  INSTALL_EXE_UPD=$(basename "${INSTALL_URL_UPD}")
fi

function install() {
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL}" -O "${TMPDIR}/${INSTALL_EXE}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # get upd file
    wget "${INSTALL_URL_UPD}" -O "${TMPDIR}/${INSTALL_EXE_UPD}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_UPD}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Unpack setup files
    7z x "${TMPDIR}/${INSTALL_EXE}" -o"${TMPDIR}/dl"
    sed -i "s|;1058|&\nPatch=$INSTALL_EXE_UPD|" "${TMPDIR}/dl/setup.ini"
    cp "${TMPDIR}/"*.msp "${TMPDIR}/dl"
    # Installs the application
    wine "${TMPDIR}/dl/setup.exe" /sAll
    # Apply reg
    # wget https://gist.githubusercontent.com/mmtrt/896cf131e3956b23e8e47a5a52f58b01/raw/e1710bbb91d8ef1da8bae5c8e2a7fe23f2e8a215/acrordr -P ${TMPDIR} && wine regedit ${TMPDIR}/acrordr && rm ${TMPDIR}/acrordr
    # Rename some files which are going rouge on closing acrordr
    # cd "$WINEPREFIX/drive_c/Program Files/Common Files/Adobe/ARM/1.0"
    # mv armsvc.exe armsvc.exe_disabled
    # mv AdobeARM.exe AdobeARM.exe_disabled
    # mv AdobeARMHelper.exe AdobeARMHelper.exe_disabled
    # cd "$progHome/AcroCEF"
    # mv RdrServicesUpdater.exe RdrServicesUpdater.exe_disabled
    # mv RdrCEF.exe RdrCEF.exe_disabled
    # Remove the cached installers & files
    rm -v "${TMPDIR}/${INSTALL_EXE}" 2>/dev/null
    rm -rf "${TMPDIR}/dl" 2>/dev/null
    rm -rf "${TMPDIR}/winetricks" 2>/dev/null
}

function install_us() {
    # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_US}" ]; then
    INSTALL_URL="${INSTALL_URL_US}"
    INSTALL_EXE=$(basename "${INSTALL_URL}")
    install
  fi
}

  action=$(yad --width 400 --entry --title "Adobe Acrobat Reader 2017" \
      --center \
      --width=400 \
      --button="Install:0" --button="Exit:1" \
      --text "Download installer:" \
      --entry "MUI")
  ret=$?

  [[ $ret -eq 1 ]] && exit 0

  case $action in
      MUI*) cmd=$(install_us) ;;
      *) exit 1 ;;
  esac

  eval $cmd 2>/dev/null
