#!/bin/bash

# acrordrdc env
progHome="$WINEPREFIX/drive_c/Program Files/Adobe/Acrobat Reader DC/Reader"
progBin="AcroRd32.exe"
progSetup="$WINEPREFIX/drive_c/Program Files/Adobe/Acrobat Reader DC/Setup Files"

$WINETRICKS --unattended mspatcha

INSTALL_URL_DE="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/XXX/AcroRdrDCXXX_de_DE.exe"
INSTALL_URL_US="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/XXX/AcroRdrDCXXX_en_US.exe"
INSTALL_URL_ES="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/XXX/AcroRdrDCXXX_es_ES.exe"
INSTALL_URL_FR="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/XXX/AcroRdrDCXXX_fr_FR.exe"
INSTALL_URL_JP="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/XXX/AcroRdrDCXXX_ja_JP.exe"
INSTALL_URL_C_DE="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/YYY/AcroRdrDCYYY_de_DE.exe"
INSTALL_URL_C_US="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/YYY/AcroRdrDCYYY_en_US.exe"
INSTALL_URL_C_ES="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/YYY/AcroRdrDCYYY_es_ES.exe"
INSTALL_URL_C_FR="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/YYY/AcroRdrDCYYY_fr_FR.exe"
INSTALL_URL_C_JP="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/YYY/AcroRdrDCYYY_ja_JP.exe"
INSTALL_URL_UPD="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/XXX/AcroRdrDCUpdXXX.msp"

# If we've been given and installer URL derive the filename
if [ -n "${INSTALL_URL_DE}" ]; then
  INSTALL_EXE_DE=$(basename "${INSTALL_URL_DE}")
fi

if [ -n "${INSTALL_URL_ES}" ]; then
  INSTALL_EXE_ES=$(basename "${INSTALL_URL_ES}")
fi

if [ -n "${INSTALL_URL_FR}" ]; then
  INSTALL_EXE_FR=$(basename "${INSTALL_URL_FR}")
fi

if [ -n "${INSTALL_URL_JP}" ]; then
  INSTALL_EXE_JP=$(basename "${INSTALL_URL_JP}")
fi

if [ -n "${INSTALL_URL_US}" ]; then
  INSTALL_EXE_US=$(basename "${INSTALL_URL_US}")
fi

if [ -n "${INSTALL_URL_UPD}" ]; then
  INSTALL_EXE_UPD=$(basename "${INSTALL_URL_UPD}")
fi

function install_de() {
    # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_DE}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_DE}" -O "${TMPDIR}/${INSTALL_EXE_DE}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_DE}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Unpack setup files
    7z x "${TMPDIR}/${INSTALL_EXE_DE}" -o"${TMPDIR}/dl"
    # Installs the application
    wine "${TMPDIR}/dl/setup.exe" /sAll
    # Apply reg
    wget https://gist.github.com/mmtrt/896cf131e3956b23e8e47a5a52f58b01/raw/097cbd0eeb836d69a84423aaef9a7ead2840a111/acrordr -P ${TMPDIR} && wine regedit ${TMPDIR}/acrordr && rm ${TMPDIR}/acrordr
    # set prefix os to xp
    $WINETRICKS --unattended winxp
    # Rename rdrcef file which is going rouge on closing acrordr
    mv "$progHome/AcroCEF/RdrCEF.exe" "$progHome/AcroCEF/RdrCEF.exe.BAK" 2>/dev/null
    # Remove the cached installers & files
    rm -v "${TMPDIR}/${INSTALL_EXE_DE}" 2>/dev/null
    rm -rf "${TMPDIR}/dl"
    rm -rf "${XDG_CACHE_HOME}/winetricks" 2>/dev/null
    rm -rf "$progSetup"
  fi
}

function install_es() {
    # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_ES}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_ES}" -O "${TMPDIR}/${INSTALL_EXE_ES}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_ES}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Unpack setup files
    7z x "${TMPDIR}/${INSTALL_EXE_ES}" -o"${TMPDIR}/dl"
    # Installs the application
    wine "${TMPDIR}/dl/setup.exe" /sAll
    # Apply reg
    wget https://gist.github.com/mmtrt/896cf131e3956b23e8e47a5a52f58b01/raw/097cbd0eeb836d69a84423aaef9a7ead2840a111/acrordr -P ${TMPDIR} && wine regedit ${TMPDIR}/acrordr && rm ${TMPDIR}/acrordr
    # set prefix os to xp
    $WINETRICKS --unattended winxp
    # Rename rdrcef file which is going rouge on closing acrordr
    mv "$progHome/AcroCEF/RdrCEF.exe" "$progHome/AcroCEF/RdrCEF.exe.BAK" 2>/dev/null
    # Remove the cached installers & files
    rm -v "${TMPDIR}/${INSTALL_EXE_ES}" 2>/dev/null
    rm -rf "${TMPDIR}/dl"
    rm -rf "${XDG_CACHE_HOME}/winetricks" 2>/dev/null
    rm -rf "$progSetup"
  fi
}

function install_fr() {
    # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_FR}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_FR}" -O "${TMPDIR}/${INSTALL_EXE_FR}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_FR}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Unpack setup files
    7z x "${TMPDIR}/${INSTALL_EXE_FR}" -o"${TMPDIR}/dl"
    # Installs the application
    wine "${TMPDIR}/dl/setup.exe" /sAll
    # Apply reg
    wget https://gist.github.com/mmtrt/896cf131e3956b23e8e47a5a52f58b01/raw/097cbd0eeb836d69a84423aaef9a7ead2840a111/acrordr -P ${TMPDIR} && wine regedit ${TMPDIR}/acrordr && rm ${TMPDIR}/acrordr
    # set prefix os to xp
    $WINETRICKS --unattended winxp
    # Rename rdrcef file which is going rouge on closing acrordr
    mv "$progHome/AcroCEF/RdrCEF.exe" "$progHome/AcroCEF/RdrCEF.exe.BAK" 2>/dev/null
    # Remove the cached installers & files
    rm -v "${TMPDIR}/${INSTALL_EXE_FR}" 2>/dev/null
    rm -rf "${TMPDIR}/dl"
    rm -rf "${XDG_CACHE_HOME}/winetricks" 2>/dev/null
    rm -rf "$progSetup"
  fi
}

function install_jp() {
    # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_JP}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_JP}" -O "${TMPDIR}/${INSTALL_EXE_JP}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_JP}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Unpack setup files
    7z x "${TMPDIR}/${INSTALL_EXE_JP}" -o"${TMPDIR}/dl"
    # Installs the application
    wine "${TMPDIR}/dl/setup.exe" /sAll
    # Apply reg
    wget https://gist.github.com/mmtrt/896cf131e3956b23e8e47a5a52f58b01/raw/097cbd0eeb836d69a84423aaef9a7ead2840a111/acrordr -P ${TMPDIR} && wine regedit ${TMPDIR}/acrordr && rm ${TMPDIR}/acrordr
    # set prefix os to xp
    $WINETRICKS --unattended winxp
    # Rename rdrcef file which is going rouge on closing acrordr
    mv "$progHome/AcroCEF/RdrCEF.exe" "$progHome/AcroCEF/RdrCEF.exe.BAK" 2>/dev/null
    # Remove the cached installers & files
    rm -v "${TMPDIR}/${INSTALL_EXE_JP}" 2>/dev/null
    rm -rf "${TMPDIR}/dl"
    rm -rf "${XDG_CACHE_HOME}/winetricks" 2>/dev/null
    rm -rf "$progSetup"
  fi
}

function install_us() {
    # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_US}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_US}" -O "${TMPDIR}/${INSTALL_EXE_US}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_US}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Unpack setup files
    7z x "${TMPDIR}/${INSTALL_EXE_US}" -o"${TMPDIR}/dl"
    # Installs the application
    wine "${TMPDIR}/dl/setup.exe" /sAll
    # Apply reg
    wget https://gist.github.com/mmtrt/896cf131e3956b23e8e47a5a52f58b01/raw/097cbd0eeb836d69a84423aaef9a7ead2840a111/acrordr -P ${TMPDIR} && wine regedit ${TMPDIR}/acrordr && rm ${TMPDIR}/acrordr
    # set prefix os to xp
    $WINETRICKS --unattended winxp
    # Rename rdrcef file which is going rouge on closing acrordr
    mv "$progHome/AcroCEF/RdrCEF.exe" "$progHome/AcroCEF/RdrCEF.exe.BAK" 2>/dev/null
    # Remove the cached installers & files
    rm -v "${TMPDIR}/${INSTALL_EXE_US}" 2>/dev/null
    rm -rf "${TMPDIR}/dl"
    rm -rf "${XDG_CACHE_HOME}/winetricks" 2>/dev/null
    rm -rf "$progSetup"
  fi
}

  action=$(yad --width 400 --entry --title "Adobe Acrobat Reader DC" \
      --center \
      --width=400 \
      --button="Install:0" --button="Exit:1" \
      --text "Select your language for installer download:" \
      --entry-text \
      "English" "French" "German" "Japanese" "Spanish")
  ret=$?

  [[ $ret -eq 1 ]] && exit 0

  case $action in
      Ger*) cmd=$(install_de) ;;
      Spa*) cmd=$(install_es) ;;
      Fre*) cmd=$(install_fr) ;;
      Jap*) cmd=$(install_jp) ;;
      Eng*) cmd=$(install_us) ;;
      *) exit 1 ;;
  esac

  eval $cmd 2>/dev/null
