#!/bin/bash

# acrordrdc env
progHome="$WINEPREFIX/drive_c/Program Files/Adobe/Acrobat Reader DC/Reader"
progBin="AcroRd32.exe"
progSetup="$WINEPREFIX/drive_c/Program Files/Adobe/Acrobat Reader DC/Setup Files/{AC76BA86-7AD7-1033-7B44-AC0F074E4100}"
prefixFont="$WINEPREFIX/drive_c/windows/Fonts"

$WINETRICKS --unattended mspatcha riched20 vcrun2015 win7

INSTALL_URL_DE="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/XXX/AcroRdrDCXXX_de_DE.exe"
INSTALL_URL_US="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/XXX/AcroRdrDCXXX_en_US.exe"
INSTALL_URL_ES="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/XXX/AcroRdrDCXXX_es_ES.exe"
INSTALL_URL_FR="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/XXX/AcroRdrDCXXX_fr_FR.exe"
INSTALL_URL_JP="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/XXX/AcroRdrDCXXX_ja_JP.exe"
INSTALL_URL_C_DE="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/YYY/AcroRdrDCYYY_de_DE.exe"
INSTALL_URL_C_US="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/YYY/AcroRdrDCYYY_en_US.exe"
INSTALL_URL_C_ES="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/YYY/AcroRdrDCYYY_es_ES.exe"
INSTALL_URL_C_FR="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/YYY/AcroRdrDCYYY_fr_FR.exe"
INSTALL_URL_C_JP="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/YYY/AcroRdrDCYYY_ja_JP.exe"
INSTALL_URL_UPD="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/XXX/AcroRdrDCUpdXXX.msp"

if [[ ! -f "$prefixFont/Segoe UI.ttf" ]]; then
  mkdir -p "$prefixFont"
  ( cd "$prefixFont"
  wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/normal/latest.ttf" -O "Segoe UI.ttf"
  wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/semibold/latest.ttf" -O "Segoe UI Semibold.ttf"
  wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/bold/latest.ttf" -O "Segoe UI Bold.ttf"
  wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/semibold/latest.ttf" -O "Segoe UI Semibold.ttf"
  wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/light/latest.ttf" -O "Segoe UI Light.ttf"
  wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/semilight/latest.ttf" -O "Segoe UI Semilight.ttf"
  wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/italic/latest.ttf" -O "Segoe UI Italic.ttf" )
fi

# If we've been given and installer URL derive the filename
if [ -n "${INSTALL_URL_UPD}" ]; then
  INSTALL_EXE_UPD=$(basename "${INSTALL_URL_UPD}")
fi

function install() {
   if wget -q --method=HEAD "${INSTALL_URL}"; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL}" -O "${TMPDIR}/${INSTALL_EXE}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Unpack setup files
    7z x "${TMPDIR}/${INSTALL_EXE}" -o"${TMPDIR}/dl"
    # Installs the application
    wine "${TMPDIR}/dl/setup.exe" /sAll
    # Apply reg
    wget --no-check-certificate -q https://gist.githubusercontent.com/mmtrt/896cf131e3956b23e8e47a5a52f58b01/raw/e1710bbb91d8ef1da8bae5c8e2a7fe23f2e8a215/acrordr -P ${TMPDIR} && wine regedit ${TMPDIR}/acrordr && rm ${TMPDIR}/acrordr
    # Rename some files which are going rouge on closing acrordr
    cd "$WINEPREFIX/drive_c/Program Files/Common Files/Adobe/ARM/1.0"
    mv armsvc.exe armsvc.exe_disabled
    mv AdobeARM.exe AdobeARM.exe_disabled
    mv AdobeARMHelper.exe AdobeARMHelper.exe_disabled
    cd "$progHome/AcroCEF"
    mv RdrServicesUpdater.exe RdrServicesUpdater.exe_disabled
    mv RdrCEF.exe RdrCEF.exe_disabled
    # Remove the cached installers & files
    rm -v "${TMPDIR}/${INSTALL_EXE}" 2>/dev/null
    rm -rf "${TMPDIR}/dl" 2>/dev/null
    rm -rf "${TMPDIR}/winetricks" 2>/dev/null
   elif [ -f "$progSetup/setup.exe" ]; then
    wget "${INSTALL_URL_UPD}" -O "${TMPDIR}/${INSTALL_EXE_UPD}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_UPD}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    mkdir -p "${TMPDIR}/temp"
    cp -r "${progSetup}/"* "${TMPDIR}/temp"
    cp "${TMPDIR}/"*.msp "${TMPDIR}/temp"
    sed -i "s|$(echo $INSTALL_URL_C_US | sed -r 's|/| |g' | awk '{print $8}')|$(echo $INSTALL_URL_UPD | sed -r 's|/| |g' | awk '{print $8}')|" "${TMPDIR}/temp/setup.ini"
    wine "${TMPDIR}/temp/setup.exe" /sAll
    sleep 5
    rm -rf "${TMPDIR}/temp" 2>/dev/null
    else
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_C}" -O "${TMPDIR}/${INSTALL_EXE_C}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_C}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # get upd file
    wget "${INSTALL_URL_UPD}" -O "${TMPDIR}/${INSTALL_EXE_UPD}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_UPD}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Unpack setup files
    7z x "${TMPDIR}/${INSTALL_EXE_C}" -o"${TMPDIR}/dl"
    rm -r "${TMPDIR}/dl/$(ls ${TMPDIR}/dl/ | grep \.msp$)"
    cp -r "${TMPDIR}/$(ls ${TMPDIR}/ | grep \.msp$)" "${TMPDIR}/dl/"
    sed -i "s|$(echo $INSTALL_URL_C_US | sed -r 's|/| |g' | awk '{print $8}')|$(echo $INSTALL_URL_UPD | sed -r 's|/| |g' | awk '{print $8}')|" "${TMPDIR}/dl/setup.ini"
    # Installs the application
    wine "${TMPDIR}/dl/setup.exe" /sAll
    # Apply reg
    wget --no-check-certificate -q https://gist.githubusercontent.com/mmtrt/896cf131e3956b23e8e47a5a52f58b01/raw/e1710bbb91d8ef1da8bae5c8e2a7fe23f2e8a215/acrordr -P ${TMPDIR} && wine regedit ${TMPDIR}/acrordr && rm ${TMPDIR}/acrordr
    # Rename some files which are going rouge on closing acrordr
    cd "$WINEPREFIX/drive_c/Program Files/Common Files/Adobe/ARM/1.0"
    mv armsvc.exe armsvc.exe_disabled
    mv AdobeARM.exe AdobeARM.exe_disabled
    mv AdobeARMHelper.exe AdobeARMHelper.exe_disabled
    cd "$progHome/AcroCEF"
    mv RdrServicesUpdater.exe RdrServicesUpdater.exe_disabled
    mv RdrCEF.exe RdrCEF.exe_disabled
    # Remove the cached installers & files
    rm -v "${TMPDIR}/${INSTALL_EXE_C}" 2>/dev/null
    rm -rf "${TMPDIR}/dl" 2>/dev/null
    rm -rf "${TMPDIR}/winetricks" 2>/dev/null
    fi
}

function install_de() {
    # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_DE}" ]; then
    INSTALL_URL="${INSTALL_URL_DE}"
    INSTALL_EXE=$(basename "${INSTALL_URL}")
    INSTALL_URL_C="${INSTALL_URL_C_DE}"
    INSTALL_EXE_C=$(basename "${INSTALL_URL_C}")
    install
  fi
}

function install_es() {
    # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_ES}" ]; then
    INSTALL_URL="${INSTALL_URL_ES}"
    INSTALL_EXE=$(basename "${INSTALL_URL}")
    INSTALL_URL_C="${INSTALL_URL_C_ES}"
    INSTALL_EXE_C=$(basename "${INSTALL_URL_C}")
    install
  fi
}

function install_fr() {
    # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_FR}" ]; then
    INSTALL_URL="${INSTALL_URL_FR}"
    INSTALL_EXE=$(basename "${INSTALL_URL}")
    INSTALL_URL_C="${INSTALL_URL_C_FR}"
    INSTALL_EXE_C=$(basename "${INSTALL_URL_C}")
    install
  fi
}

function install_jp() {
    # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_JP}" ]; then
    INSTALL_URL="${INSTALL_URL_JP}"
    INSTALL_EXE=$(basename "${INSTALL_URL}")
    INSTALL_URL_C="${INSTALL_URL_C_JP}"
    INSTALL_EXE_C=$(basename "${INSTALL_URL_C}")
    install
  fi
}

function install_us() {
    # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_US}" ]; then
    INSTALL_URL="${INSTALL_URL_US}"
    INSTALL_EXE=$(basename "${INSTALL_URL}")
    INSTALL_URL_C="${INSTALL_URL_C_US}"
    INSTALL_EXE_C=$(basename "${INSTALL_URL_C}")
    install
  fi
}

  action=$(yad --width 400 --entry --title "Adobe Acrobat Reader DC" \
      --center \
      --width=400 \
      --button="Install:0" --button="Exit:1" \
      --text "Select your language for installer download:" \
      --entry-text \
      "English" "French" "German" "Japanese" "Spanish")
  ret=$?

  [[ $ret -eq 1 ]] && exit 0

  case $action in
      Ger*) cmd=$(install_de) ;;
      Spa*) cmd=$(install_es) ;;
      Fre*) cmd=$(install_fr) ;;
      Jap*) cmd=$(install_jp) ;;
      Eng*) cmd=$(install_us) ;;
      *) exit 1 ;;
  esac

  eval $cmd 2>/dev/null
